version: "3.3"
services:
  backend:
     image: gitlab-registry.lrde.epita.fr/soduco/directory-annotator-back
     build:
      context: ..
      dockerfile: ./docker/deploy-debian-stable.dockerfile
     ports:
        - "${REVERSE_PORT_BACK}:8000"
     env_file:
        - .env
     environment:
        - SODUCO_SETTINGS=/app/settings.cfg
        - SCRIPT_NAME=/soduco/directory-annotator/backend
        - GUNICORN_CMD_ARGS=--workers=2 --preload
     secrets:
        - auth_tokens
     volumes:
        - type: bind
          source: ${PATH_DIRECTORIES}
          target: "/data/directories"
          read_only: true
        - type: bind
          source: ./settings-back.cfg
          target: "/app/settings.cfg"
        # - type: volume
        #   source: soduco-annotations-data
        #   target: "/data/annotations"
        #   volume:
        #     nocopy: true
  # FIXME si j'active le service storage, je n'arrive plus à contacter le backend (parfois l'inverse)…
  storage:
     build:
      context: .
      dockerfile: deploy_storage_autofetch.dockerfile
     ports:
        - "${REVERSE_PORT_STORAGE}:8000"
     env_file:
        - .env
     environment:
        - SODUCO_SETTINGS=/app/settings.cfg
        - SCRIPT_NAME=/soduco/directory-annotator/storage
     secrets:
        - auth_tokens
     volumes:
        - type: bind
          source: ${PATH_DIRECTORIES}
          target: "/data/directories"
          read_only: true
        - type: bind
          source: ./settings-storage.cfg
          target: "/app/settings.cfg"
        - type: volume
          source: soduco-annotations-data
          target: "/data/annotations"
          volume:
            nocopy: true

volumes:
  soduco-annotations-data:

secrets:
  auth_tokens:
    file: .secret-keys
